### ISSUE TITLE
Updating the aht10_datasheet.pdf

### ISSUE THREAD

**Issue by Tonny-Y** [RT-Thread-packages/aht10#10]
I just find that the aht10_datasheet.pdf had been updated in www.aosong.com, and the old version had actually some mistakes making users puzzled.
[aht10_datasheet_v1_1_181220.pdf](https://github.com/RT-Thread-packages/aht10/files/3388548/aht10_datasheet_v1_1_181220.pdf)

**Comment by armink** [comment]
you can give a github pr to update this :)
